# tasks file
---
- name: install | dependencies
  apt:
    name: "{{ new_relic_servers_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - new-relic-servers-install-dependencies
