# tasks file for new-relic-servers
---
- name: install | dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ new_relic_servers_dependencies }}"
  tags:
    - new-relic-servers-install-dependencies
