# tasks file
---
- name: repository
  ansible.builtin.import_tasks: repository.yml
  tags:
    - configuration
    - new-relic-servers
    - new-relic-servers-repository

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - new-relic-servers
    - new-relic-servers-install

- name: configure
  ansible.builtin.import_tasks: configure.yml
  tags:
    - configuration
    - new-relic-servers
    - new-relic-servers-configure

- name: start and enable service
  ansible.builtin.service:
    name: newrelic-sysmond
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - new-relic-servers
    - new-relic-servers-start-enable-service
