# tasks file for new-relic-servers
---
- include: repository.yml
  tags:
    - configuration
    - new-relic-servers
    - new-relic-servers-repository

- include: install.yml
  tags:
    - configuration
    - new-relic-servers
    - new-relic-servers-install

- include: configure.yml
  tags:
    - configuration
    - new-relic-servers
    - new-relic-servers-configure

- name: start and enable service
  service:
    name: newrelic-sysmond
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - new-relic-servers
    - new-relic-servers-start-enable-service
