# tasks file for new-relic-servers
---
- name: repository | add public key
  apt_key:
    id: 548C16BF
    url: https://download.newrelic.com/548C16BF.gpg
    state: present
  tags:
    - new-relic-servers-repository-public-key

- name: repository | add
  apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
    mode: 0644
  with_items: "{{ new_relic_servers_repositories }}"
  tags:
    - new-relic-servers-repository-add
